// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "BaseDungeonInstance.generated.h"

/**
 * A base class for dungeon instances. It is not meant to be used directly.
 * Contains high-level logic for deciding whether to spawn dungeons at runtime or design time.
 */
UCLASS()
class DUNGEONFORGE_API ABaseDungeonInstance : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABaseDungeonInstance();

	/**
	 * Generate a layout based on the current parameters. Saves the layout to be spawned later.
	 */
	UFUNCTION(CallInEditor)
	virtual void GenerateLayout();
	
	/**
	 * Use the layout generated by GenerateLayout() to spawn the dungeon.
	 */
	UFUNCTION(CallInEditor)	
	virtual void SpawnDungeon();
	
	/**
	 * Generates and spawns the dungeon all at once.
	 */
	UFUNCTION(CallInEditor)	
	virtual void GenerateDungeon();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;
};
